### ISSUE TITLE
Add Event Organizers & Braintree hosts reserve the right to expel

### ISSUE THREAD

**Issue by GovInTrenches** [chihacknight/chihacknight.org#120]
Under `If a participant engages in harassing behavior, the event organizers may take any action they deem appropriate, including warning the offender or expulsion from Chi Hack Night.` add 

`Please be aware that Chi Hack Night hosts or Braintree staff may remove participants _at will for any reason_ and _will_ remove any user that Chi Hack Night hosts or Braintree staff deems to be violating the Code for Conduct or are being disruptive. This policy also extends to the Chi Hack Night Slack instance.`  

Adding this to recognize that Braintree staff don't actually need a reason to expel anyone since it's their venue. Also adding that Chi Hack Night hosts also reserve this right in the event that a known trouble-maker appears. Alternatively, if we ever have a situation where somebody wants to litigate that they weren't harassing anyone, but it becomes obvious that the person needs to be removed - we can do so and point to that section as 'we can and are doing this' 

This [language](https://github.com/codeforamerica/slackpolicy) comes from the Code for America Slack Policy which takes a similar approach. 

Also added a line that extends the Code of Conduct to our Slack channel.

**Comment by stevevance** [comment]
How would someone know who is a host and who isn't?

**Comment by derekeder** [comment]
I was thinking, perhaps we expand the list of people who have leadership roles at Chi Hack Night. This would include duties like:

- co-hosts
- event planning
- braintree host

Thoughts?

**Comment by GovInTrenches** [comment]
What @derekeder said re: including leadership roles on the website. Also agree with @stevevance about including Google Groups in the language as well. 

The reason that I say 'co-host' is that during the event the co-hosts are in charge of run-of-show and have better visibility. The other thing that we _could_ think about doing is creating name badges for hosts and breakout group leaders. Code for San Francisco has a whole color-coded system that they use. Permanent name badges for the core team, red name badges for returning members, and blue ones for new people (so that people can welcome thing.) 

At the very least, having a co-host badge might be useful for people who are wondering who is in charge and so they can ask questions. Breakout leader badges would also be useful too.

**Comment by derekeder** [comment]
I started a pull request to add all the additional people who are now officially helping organize Chi Hack Night: https://github.com/chihacknight/chihacknight.org/pull/122

I didn't add anyone from Braintree. Not sure if it's really necessary

**Comment by derekeder** [comment]
this looks to have been addressed in #122
