### ISSUE TITLE
Cancelled speaker (& other scenarios) standards

### ISSUE THREAD

**Issue by shua123** [chihacknight/chihacknight.org#154]
Should we standardize how we present when a speaker has cancelled? In the case of 10/9/18 there was a last minute speaker cancellation so "CANCELLED" was added to the event title. This may cause some people who just glance at the title to think that the whole event is cancelled not just the speaker. Is there a better way we could indicate a cancelled speaker but not cancelled event?

Are there other scenarios that we should have standards for?

![image](https://user-images.githubusercontent.com/1593537/47944746-8b347b80-decb-11e8-9474-4dead6e1e906.png)

**Comment by derekeder** [comment]
Agreed this is misleading. How about CANCELLED PRESENTATION

**Comment by derekeder** [comment]
To do: @shua123 document this in the Readme.
