### ISSUE TITLE
Event template: Drive ASL interpreter text from variable

### ISSUE THREAD

**Issue by shua123** [chihacknight/chihacknight.org#188]
We have an asl_provided variable but we are not using it for the "**ASL** This event will/will not have an American Sign Language interpreter" text. This is manual text change sometimes gets missed. It makes sense to make this text auto update based on the variable.

**Comment by shua123** [comment]
For the past couple events I have updated the text to use the variable:
`**ASL** This event will {% unless page.asl_provided %} not {% endunless %}have an American Sign Language interpreter.`

This whole RSVP/ASL/Food section should really be moved to the event template, especially as we move to a CMS. Moving it to the event template will mess up previous events though so we need to figure out how to handle that. Maybe version the events template or have it display that section if after a certain date?

**Comment by easherma** [comment]
@shua123 lets open a separate issue for moving other sections, and stick to this one pertaining just to ASL stuff?
