### ISSUE TITLE
Eventbrite registration flow issues: no sign-in, and misformatting on thank-you page

### ISSUE THREAD

**Issue by kfogel** [chihacknight/chihacknight.org#256]
When registering to attend a Chi Hack Night from the https://chihacknight.org/ front page, I've noticed two new issues.  I suspect they're both due to some change in Eventbrite's registration flow APIs, but I don't know that for sure.

1) There is no longer a chance to sign in to Eventbrite during the registration process.  The sign-in button just never appears (it used to).  So every time I end up canceling my first attempt at registration, then opening up a new tab and logging in to Eventbrite there, then restarting a fresh registration from ChiHackNight.org -- now my browser tells Eventbrite I'm already signed in, so when the registration form pops up this time it has my information all already filled in.

2) The "thank you" page after registration is showing raw HTML now:

```
Thanks for RSVPing!<br/><br/>For more information on the Chi Hack Night, check out:<br/><br/>Chi Hack Night website <br/>chihacknight Google Group <br/>@ChiHackNight on Twitter
```

See attached image.
![chihacknight-eventbrite-reg-thank-you-raw-html-2019-12-02](https://user-images.githubusercontent.com/401111/69981381-d61e2980-14f7-11ea-816b-0089ee7cf2af.png)

**Comment by derekeder** [comment]
not sure when, but this was fixed several years ago. closing
