### ISSUE TITLE
Resources!

### ISSUE THREAD

**Issue by derekeder** [chihacknight/chihacknight.org#28]
Created a page for developer resources:

http://opengovhacknight.org/resources.html

Started with a list of APIs and data portals available in Chicago. Should continue to flesh out with:

* tutorials
* tools
* data wrappers
* process overview of creating a civic app
* @smartchicago resources (server space, etc)

@GovInTrenches, @jpvelez, @evz, @miguelabarbosa, @kfogel - I welcome your feedback!

**Comment by GovInTrenches** [comment]
Could we move the 'free hosting/tools' to the space below or just above portals? Right now it's buried underneath the list of other datasets.

**Comment by derekeder** [comment]
Closing for now as this thread is over a year old with no changes.
