### ISSUE TITLE
add site search

### ISSUE THREAD

**Issue by derekeder** [chihacknight/chihacknight.org#320]
Our site has grown over the years to have about 500 pages. I think we are long overdue for adding search capabilities.

This is a useful post that details one approach: https://blog.webjeda.com/instant-jekyll-search/ (demo: https://blog.webjeda.com/demo/instant-jekyll-search/)

An alternative would be to use Google's Custom Site search: https://programmablesearchengine.google.com/about/

**Comment by easherma** [comment]
That first approach seems simple enough to be worth trying! 

Algolia also does some handy search stuff, and we'd likely fit under their free pricing tier. 

I hadn't heard of Google's Custom Site search, though I imagine the trade-off there is giving Google data on what people are searching on our site. Which is probably not a dealbreaker, just an ideological trade-off. 

This doesn't help short-term, but this is also on my short list of 'reasons why it might be time to build a better website' 
:-D While something like Elasticsearch would be overkill, if we had our content in a relational database (say a Django app) it would be easy enough to have better search functionality.

**Comment by derekeder** [comment]
closed via #322
