### ISSUE TITLE
Update all presentation templates to highlight YouTube automatic closed captioning

### ISSUE THREAD

**Issue by shua123** [chihacknight/chihacknight.org#475]

**Comment by shua123** [comment]
I'm debating where to put this. On https://github.com/chihacknight/chihacknight.org/tree/closed-captioning I added it to the livestream mention in the main body and the right sidebar 
![image](https://user-images.githubusercontent.com/1593537/213942773-871844fd-acd1-4198-90f5-a3886a70dfe8.png)

Should I have a line at the bottom like the ASL one too (or instead of these other ones)?

What do you think? @derekeder @lauriemerrell

**Comment by lauriemerrell** [comment]
I think that maybe it doesn't need to be in the sidebar? And I do think that if we are keeping the note about ASL interpretation not being available for online, the closed captioning note should be included alongside to clarify what options are available in one place. If we are removing the note about ASL interpretation from online events, then I think just including it in the header is ok. But I would also be curious for @derekeder's thoughts given that he's been kind of taking point on this topic.

**Comment by derekeder** [comment]
Agreed we don't need it in the sidebar. If we have the note about ASL at the footer, we should also include a note about closed captioning next to it.

**Comment by shua123** [comment]
@derekeder @lauriemerrell Updated version here: https://deploy-preview-494--chihacknight-website.netlify.app/ Checkout upcoming remote and hybrid events.

**Comment by lauriemerrell** [comment]
New version looks good to me, thanks Josh!

**Comment by shua123** [comment]
This is now in production.
