### ISSUE TITLE
Adam Hecktman's Face Makes The Site Slow

### ISSUE THREAD

**Issue by vkoves** [chihacknight/chihacknight.org#502]
After going to the [Board of Director page](https://chihacknight.org/board-of-directors.html) I noticed images loaded in slowly, and it turns out Adam's photo in particular is why:

https://user-images.githubusercontent.com/3187531/227612919-126b5677-5231-4de0-8627-10de09ab1d93.mp4

Here's a screenshot from the Network tab showing that his photo is 1.5 MB.

![Screenshot from 2023-03-24 13-43-43](https://user-images.githubusercontent.com/3187531/227612902-35d5fd2e-6475-4d65-b11b-daa8456a7907.png)

I'd suggest cropping it to a more reasonable size, maybe around 300px by 300px

**Comment by derekeder** [comment]
good call - we should resize that pic

**Comment by shua123** [comment]
Fixed with c6c5d6142d5899fc03c38d7753ccf8858e0ff062
