### ISSUE TITLE
Add The Chicago Civic Innovation Ecosystem section to FAQ 

### ISSUE THREAD

**Issue by GovInTrenches** [chihacknight/chihacknight.org#67]
Need a paragraph to talk about the City of Chicago (link to portal, twitter), Cook County (link to portal, twitter), ChiHackNight, Smart Chicago (link to blog, infrastructure resources), and Code for America (national connections, links to summit speeches, and a plug for 'find a hack night near you' which would go to the Brigade map.

**Comment by GovInTrenches** [comment]
I'll convert the speech 'http://civicwhitaker.com/2015/03/28/building-the-civic-innovation-ecosystem-notes-from-the-civic-tech-forum/' into something that explains that not all projects are 'hack night' projects - but that hack night is a gathering place and an organizing force.

**Comment by derekeder** [comment]
old issue. closing it out
