### ISSUE TITLE
Home page says "Next Chi Hack Night:" while displaying previous hack night

### ISSUE THREAD

**Issue by shua123** [chihacknight/chihacknight.org#77]
![next-hack](https://cloud.githubusercontent.com/assets/1593537/7995203/a009a7e8-0ad9-11e5-9006-ecaf3e408433.JPG)

**Comment by derekeder** [comment]
Jekkyl is a static site, and is only updated when changes are deployed. No simple fix for this, unfortunately. Flagging as wontfix
