### ISSUE TITLE
Other Open data sources not displaying

### ISSUE THREAD

**Issue by shua123** [chihacknight/chihacknight.org#78]
Other Open data source list is not loading on http://chihacknight.org/data-resources.html

**Comment by derekeder** [comment]
Fixed via 441b0b8e16066045d873d636cf69772684c76ba4

Google Docs recently broke the publish to CSV feature that we were using. When a document is 'upgraded to the new Google Sheets' CSV publishing stops working.

![screen shot 2015-06-09 at 11 13 01 am](https://cloud.githubusercontent.com/assets/919583/8063039/938c4990-0e98-11e5-8e66-f1a8a4068e94.png)

:-1: Google
