### ISSUE TITLE
Twitter cards for event pages

### ISSUE THREAD

**Issue by fgregg** [chihacknight/chihacknight.org#80]
http://davidensinger.com/2013/04/supporting-twitter-cards-with-jekyll/

**Comment by derekeder** [comment]
I think this is something we're already doing.

<img width="641" alt="screen shot 2015-07-05 at 5 52 32 am" src="https://cloud.githubusercontent.com/assets/919583/8511404/11c7d450-22da-11e5-88da-30a27d60b4ba.png">

**Comment by fgregg** [comment]
Yup.
