### ISSUE TITLE
'everyone is welcome' text

### ISSUE THREAD

**Issue by derekeder** [chihacknight/chihacknight.org#84]
The [current text](http://chihacknight.org/about.html#everyone) calls out techies vs non-techies, but we should go further.

Suggestions from @cathydeng:
- acknowledge and welcome those who feel [impostor syndrome](https://en.wikipedia.org/wiki/Impostor_syndrome)
- if you're from a background which isn’t well-represented in most geeky meetups 
- we can say everyone is welcome but tech/data nerds are still gona feel more comfortable coming, and they probably always will, but we can do more to minimize that comfort-level disparity

**Comment by stevevance** [comment]
I don’t think we need an imposters welcome message. We have a Code of Conduct that addresses this. Maybe we can extract text from that document to incorporate on our website, in the "About" or "Community" pages.

**Comment by benwilhelm** [comment]
I agree that we don't necessarily need to say "Imposters Welcome", but the current phrasing...

> We encourage non-technical folks to pair up and learn from our community's designers and developers.

...still implies that the non-technical folks are there to attach themselves to the technically inclined, and that the technically inclined will be the drivers of action. Instead we should stress that good project ideas can be conceived and driven by folks with all kinds of backgrounds. Maybe something like:

> Not a techie?  **That's OK!**  We're a collaborative space driven to solve problems for the city and its residents, and we know that the best ideas will come from a broad range of experience and backgrounds. There is a place for you here.

**Comment by derekeder** [comment]
this is stale. closing.
