### ISSUE TITLE
Potentially entry point projects

### ISSUE THREAD

**Issue by fgregg** [chihacknight/chihacknight.org#91]
- [ ] look at cook for Chicago's budget
- [ ] visualisations using the OCD chicago api
- [ ] Twitter bots for civil right suites against the city
- [ ] visualizations with the illinos sunshine API

**Comment by fgregg** [comment]
- [ ] Looking for "beat effects" in police data. What effect does the police beat have on crime reports. Can we see traces of organizational culture
- [ ] Characterize police districts by crime report mix (Latent Dirichlet Allocation)

**Comment by derekeder** [comment]
stale. closing
