### ISSUE TITLE
Open source projects and people not loading

### ISSUE THREAD

**Issue by pjsier** [chihacknight/chihacknight.org#96]
[Open source projects](http://chihacknight.org/open-source-projects.html) and [open source people](http://chihacknight.org/open-source-people.html) are both stuck trying to load data. I didn't get an error message, but after poking around for a bit it looks like http://worker.chihacknight.org is down. I'm happy to try and make a fix, but not sure if it can be fixed from this repo

**Comment by derekeder** [comment]
Thanks for reporting this @pjsier! Looking into it

**Comment by derekeder** [comment]
The server that was running this worker was shut down. We plan on getting it back online tomorrow.

**Comment by pjsier** [comment]
@derekeder awesome, glad to hear it!

**Comment by derekeder** [comment]
Fixed!
