### ISSUE TITLE
Is it still appropriate to say ChiHackNight is organized by members of "Open City"?

### ISSUE THREAD

**Issue by stevevance** [chihacknight/chihacknight.org#99]
On the Contact and About pages there are some things that don't seem current anymore. 
- Juan-Pablo has equal billing on the [Contact page](http://chihacknight.org/contact.html). I think it should just be Derek and Christopher. 
- Juan-Pablo probably shouldn't be contacted by someone who's looking to communicate with an organizer of CHN (it's great to recognize his past contributions, but I don't think he belongs on a Contact page; he's mentioned on the About page, and I think that's a better place to mention him)
- Is "Open City" still a thing, and is it still relevant to the production of ChiHackNight? "Open City" hasn't published an app under this name in a while, and there's more people than members of Open City that help organize different aspects of CHN. 
- Who are the members of Open City?
- On the [About page](http://chihacknight.org/about.html#organized), it says that CHN is organized by Derek and Christopher. That is true. I believe it's also organized by the dozens of breakout group leaders.

**Comment by derekeder** [comment]
@stevevance thanks for bringing this up. Definitely time for an update on this content. Let's discuss at next week's leadership meeting

**Comment by derekeder** [comment]
@GovInTrenches can you provide a brief updated bio for the contact page?

http://chihacknight.org/contact.html

**Comment by derekeder** [comment]
@stevevance I made a few changes addressing these suggestions. haven't pushed live yet.

**Comment by stevevance** [comment]
@derekeder I think all of the changes are good. 

I think there's an inconsistency here:
1. "Chi Hack Night finances are administered under DataMade, LLC." -> This is very clear. 
2. "administered by DataMade and supported by our amazing sponsors" -> This is less clear. 

Financial administration is one kind of common administration. What are others? Or, a different question is, since "administered" is used generally here, "What else does DataMade administer for CHN?"

The question is really, what administration is there to do? There's accepting money from sponsors, and paying the video crew. If DataMade is only administering financial aspects – there's a case to be made here that the open Leadership Council administers other things – then I think it's correct to have both statements the same. Can you add "fiscally sponsored by DataMade" to the second item?

Although "fiscally sponsored by DataMade" reads a little funny. It could be:

> Chi Hack Night is organized by Derek Eder, Christopher Whitaker and members of our Leadership Council, hosted at Braintree, and supported by our amazing sponsors. DataMade is the fiscal sponsor.

**Comment by GovInTrenches** [comment]
Whitaker Bio: 

Christopher Whitaker serves as the Brigade Program Manager for Code for America. Previously, Whitaker helped run a field office for the Illinois Department of Employment Security during the recession. He holds a Masters of Public Administration from DePaul University and a Bachelors of Arts in political science from Sam Houston State University. Previously, Whitaker served with the U.S. Army in Iraq as a mechanized infantryman. 

Feel free to chop that down to match spacing requirements.

**Comment by derekeder** [comment]
@stevevance good suggestion for the home page. will do.

@GovInTrenches thx! yes i might need to shorten it a bit, but this is good!

Both changes will be made live this morning
